#!/usr/bin/python

#################################################################################################
#      ARITHMETIC PROGRESSION-series generated by adding a common diference to the preceding term
#                             Name : Faith Njuguna
#                             Date : 27/05/2022
#################################################################################################

#first n terms of AP
#a = first number, d = common difference, n = number of terms
a = (int(input("Enter the first number:")))
d = (int(input("Enter the common difference:")))
n = (int(input("Enter the number of terms:")))

for i in range (1,(int(n+1))):
    n_term = a + (i-1)*d
    print(n_term)

sum_n = (n_term/2)*(2*a + (n-1)*d)
print(sum_n)


